name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Hoặc branch bạn muốn deploy từ đó
    
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
      - '_dockerfiles/**'
      - 'docker-compose.yml'
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Connect to Azure VM and Execute Command 
      env:
        AZURE_VM_IP: ${{ secrets.VM_IP }}
        AZURE_VM_USER: ${{ secrets.VM_USER }}
        AZURE_VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
      run: |
        ssh $AZURE_VM_USER@$AZURE_VM_IP
        AZURE_VM_PASSWORD
        cd mpcoin
        git pull
        docker-compose up -d

  #  need to make .env file instead of hard code in docker-compose.yml
        